### ISSUE TITLE
Investigate table partitioning or additional database tuning.

### ISSUE THREAD

**Issue by cacraig** [18F/crime-data-api#151]
Possibilities:

- Materialized view(s) + DB Trigger to refresh.
- Partitioning large tables by nibrs_incident by something. I think it might be interesting to explore partitioning nibrs_incident by agency State location. This would speed up queries that are against specific states, but slow down queries that span multiple states.

**Comment by harrisj** [comment]
I think this is a good potential area to explore and you are right about the potential issues. In some ways, we are in a bit of a Catch-22 since we want to let users run any conceivable query like they would with SQL but we also want to be super fast. Furthermore, deciding the API will directly influence the frontend interface and I don't think we want to constrain them with our choices.

Personally, in my ideal world we might transition away from the open-ended API queries we have no to more specific ones that are tailored to the general data being used in the frontend. This would mean going from "here's one endpoint for all your incident data" to "here's an incident endpoint for generating the data used on those charts" or such. Then we could focus specifically on optimizing those. But that just might be me.

**Comment by LarryBafundo** [comment]
moving to this backlog as it may not be necessary depending on the outcome of issues 148-150

**Comment by LarryBafundo** [comment]
@catherinedevlin is this issue still relevant? I know it was dependent on some of the work you were finishing up at the end of the year.

**Comment by catherinedevlin** [comment]
@cacraig has picked up the torch on this one... I'm not sure how he wants to describe his (impressive!) ongoing work into getting all this data rapidly available, whether the ongoing work should be a separate ticket or considered part of this.
