### ISSUE TITLE
Define browser & device testing matrix for CDE 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#207]
The first iteration of the Crime Data Explorer should support all modern web browsers, plus older versions of IE, based on what is used by CJIS & FBI HQ today. 

In terms of devices, we should focus our testing on the devices that were most commonly used to access the UCR website in 2016. See this analytics report for more information: https://docs.google.com/document/d/1C1adR_b0IVhAapRkBFs3NlacIMSO2IHAN7iWNQid4aU/edit 

The report mentions that the CDE should support the last 4 versions of all browsers, which would include IE 8. We should make the case that only newer versions should be supported, especially if they are already in use by they FBI, and explain how testing across too many browsers and devices will take away from our ability to add features and functionality for the MVP.

**Comment by jeremiak** [comment]
Here is some data from [analytics.usa.gov](https://analytics.usa.gov) using 2.19 billion visits over the last 90 days across a wide array of Federal webpages.

Browser | Percent of visits
--|--
Chrome | 45.3%
Safari | 24.2%
Internet Explorer (total) | 15.8%
IE 7.0 | 1%
IE 8.0 | 0.3%
IE 9.0 | 0.4%
IE 10.0  | 0.4%
IE 11.0  | 13.6%
Other | < 0.1%
Firefox | 7.5%
Edge  | 3.4%
Safari (in-app) | 1.7%
Other | 2.2%

By explicitly supporting Chrome, Safari, IE 10+, Firefox and MS Edge we cover 94.4% of the users represented in the data.

Extending support to IE 7, 8, and 9 would yield just 1.7% of users and could significantly decrease the amount or fidelity of features we can release with the MVP because those browser versions are particularly costly to develop for.

The idea of supporting the last four versions of a browser feels arbitrary, especially when it comes to a browser landscape with "evergreen" browsers and where IE has been replaced with Edge. If we include Edge as the latest version of Internet Explorer (which, in many ways it is) then the four latest browsers extends to just include IE 9. With just 0.4% of users in the analytics snapshot from above, IE 9 would increase the required time for features and therefore slow down the pace of MVP development.

Is it possible for the FBI to give us a breakdown of their webpage analytics with individual versions of the browsers broken out so we can make a more informed decision?

**Comment by LarryBafundo** [comment]
Thanks @jeremiak this is great. I'll follow-up with Lori, although she's out for most of the day today.

**Comment by konklone** [comment]
Also, some of that IE7 number is actually going to be newer IE clients in Compatibility Mode.

**Comment by LarryBafundo** [comment]
here's the latest data from UCR analytics: 

<img width="341" alt="screen shot 2016-12-21 at 2 44 01 pm" src="https://cloud.githubusercontent.com/assets/15899668/21403733/0e40db12-c78c-11e6-849c-edc2bf744b04.png">

<img width="365" alt="screen shot 2016-12-21 at 2 44 22 pm" src="https://cloud.githubusercontent.com/assets/15899668/21403735/115ab174-c78c-11e6-8a02-5c336bd2fdae.png">

<img width="343" alt="screen shot 2016-12-21 at 2 44 31 pm" src="https://cloud.githubusercontent.com/assets/15899668/21403739/1885515c-c78c-11e6-9e63-299fcd946240.png">

<img width="418" alt="screen shot 2016-12-21 at 2 44 37 pm" src="https://cloud.githubusercontent.com/assets/15899668/21403743/1c0bdf4e-c78c-11e6-9b3a-c41a7131f4a1.png">

**Comment by LarryBafundo** [comment]
Based on this data, let's move forward with the assumption that we'll cover the following, per Jeremia's earlier comment in the thread: 

"By explicitly supporting Chrome, Safari, IE 10+, Firefox and MS Edge we cover 94.4% of the users represented in the data.

Extending support to IE 7, 8, and 9 would yield just 1.7% of users and could significantly decrease the amount or fidelity of features we can release with the MVP because those browser versions are particularly costly to develop for."

I'll document and make the case the Lori and team so we have it in writing.

**Comment by jeremiak** [comment]
That looks great @LarryBafundo - Going to close this issue now and add our conclusion to the README.
