### ISSUE TITLE
Relationship loading

### ISSUE THREAD

**Issue by jmcarp** [18F/crime-data-api#280]
Hi! I was experimenting with using github.com/jmcarp/nplusone with this project for a tech talk and noticed a bunch of lazy-load warnings. For example, the `/agencies` endpoint serializes results with the [RefAgencySchema](https://github.com/18F/crime-data-api/blob/master/crime_data/common/marshmallow_schemas.py#L278-L294), which serializes a handful of relationships that aren't eager-loaded (although most are). Is that intentional--for example, is it faster to load the `tribe` relationship in a separate query for each agency than with a join or subquery?

Just curious--let me know if I'm misreading. Hopefully I can learn from this project to improve `nplusone` 😄 

@catherinedevlin

**Comment by jmcarp** [comment]
?

@LarryBafundo

**Comment by harrisj** [comment]
Some of these schema aren't really being used in production anymore (we have instead denormalized them into materialized views or such), so I suppose we could revisit some of this loading once we get past the MVP. I myself have been vexed by how much _eager_ loading is happening for some other models since that means joining in a bunch of tables that aren't being used.

**Comment by harrisj** [comment]
To clarify further, this is not really a great project to use as an example, because it is denormalized far more than many RESTful projects and is much larger than many RESTful projects often are, so eager loading can quickly lead to performance issues, as generally desirable as it usually is. That said, there are ways we can optimize it further and this might be something to discuss in a few weeks?
