### ISSUE TITLE
National NIBRS dimensions count are suspect

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#389]
I wanted to spot check that API endpoint. I made the following request `https://crime-data-explorer.fr.cloud.gov/api/victims/count/national/offender_relationship` but it showed that there was a single incident in 2014 where "Victim Was Boyfriend/Girlfriend".

Is that correct? It seems pretty low for the national count.

Originally from [18F/crime-data-explorer#274](https://github.com/18F/crime-data-explorer/issues/274#issuecomment-281420907)

**Comment by harrisj** [comment]
I am looking into this now

**Comment by harrisj** [comment]
I think what is happening here is since there is no `offense_name` specified in the query, the API is returning a breakdown of that `offender_relationship` by offense. So, you might see this

```
{
"count": 2,
"offender_relationship": "Victim Was Acquaintance",
"offense_name": "Intimidation",
"year": "2014"
}
```

if your request is just taking the year and storing the count for it in a hash, it would overwrite with a single record's count multiple times (I'm just guessing because this is something I would do). Did you want to attach an `explorer_offense` to this query? Is there a specific one I should know?

**Comment by harrisj** [comment]
Were we able to clarify this one?

**Comment by LarryBafundo** [comment]
@harrisj, @jeremiak i believe we addressed this in the last sprint through a separate fix. am i right?

**Comment by harrisj** [comment]
I think this was fixed?
