### ISSUE TITLE
Georgia reports a small number of incidents of rape between 2004 and 2014?

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#426]
<img width="820" alt="screen shot 2017-03-15 at 11 51 23 am" src="https://cloud.githubusercontent.com/assets/780941/23957457/cc8aa136-0975-11e7-9b0d-2c52c048a79c.png">

Explorer URL:
https://crime-data-explorer.fr.cloud.gov/explorer/georgia/rape

**Comment by harrisj** [comment]
This is like the #427, in that the issue here is limited participation in NIBRS. In this, case Georgia had only one agency (Norcross PD) that submitted via NIBRS. What is especially weird is the agency submitted NIBRS reports from 2001-2008 and then switched to submitting only SRS from 2009 onwards (meaning that 0% report NIBRS for Georgia in 2009 onwards)
