### ISSUE TITLE
Create new denormalized table for agency annual counts

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#448]
This will be a similar approach to reta_month_offense_subcat_summary

**Comment by harrisj** [comment]
I figure it might have these columns

|column|notes|
|-|-|
|agency_id||
|year||
|month||
|state_id||
|state_postal_abbr|grouped with state_id|
|months_reported|0-12|
|nibrs_months_reported|0-12|
|population||
|classification (property, violent)||
|offense_category|(do we need this?)|
|offense_code||
|offense_name||
|offense_subcat_code||
|offense_subcat_name||
|reported/actual/etc.||

This would do the same grouping rollups like the `reta_month_offense_subcat_summary` but it might not scale since there are a lot of agencies. Some tweaks might be to not include agencies that are covered by others. We probably could also keep the `month` rows out and groupings.

**Comment by LarryBafundo** [comment]
@harrisj as part of this sprint we want to validate (or invalidate) the value AND feasibility of providing an agency-level perspective, so we should definitely assess the scalability of the approach you describe above.

**Comment by harrisj** [comment]
I think I will need @cacraig's expert assistance on this one to see how bad it might be to create, although I think once it is created, it might be scalable enough for our purposes.

**Comment by cacraig** [comment]
@catherinedevlin ran into the issue of their just being too many cities (or agencies) in this case to precompute these groupings.  With state their are only 59 entries to account for... with agencies there are ~23,706 (probably less if we only count those that are full-reporters).  

the reta_month_offense_subcat_summary table as is contains ~2,000,000 rows.

If we apply the same methodology for agencies:
nA = Number of agencies = ~23,000
nM = Number of data Months = ~600
nO = Number of Offense groupings = ~60

nT = (nA * nM * nO) = ~828,000,000 rows => 133 GB table (give or take a few)

I think we may need to rethink this one a bit. I think we may be better off:
(1) Denormalizing reta_month_offense_subcat (adding in all the offense + agency metadata + flattening year + month into a datetime field) + Partitioning by year or state (my favorite).
(2) Filtering out non-100% reporting agencies.
(3) Adding a Unique Index on (agency_id, datetime)
(4) Profit?

I think this methodology will only work if are running queries that hit the indexes. 

Additionally, we can possibly use https://github.com/citusdata/cstore_fdw - I have used it before on time series data. It may fit our use case pretty well. It has a tradeoff though because it throws pretty much all index support out the window (in exchange for fast range queries + compression).

**Comment by harrisj** [comment]
Thanks, this makes a lot of sense! It sounds like we should not support monthly groupings (only annual counts) and limit to just offenses and not offense_subcat codes. That should cut down the results to at most ~23K * 56 * 11 = 14,168,000 rows which is a little better? Of course to generate, we would still need to group the offense subcat counts for a month into offense counts for a year, so that might be an onerous job to run...

**Comment by cacraig** [comment]
Ah I see, yeah if we stick to annual counts, and offenses. This will make sense. I am sure that only showing full-reporters will reduce it as well.

If we partition the resultant table by some heuristic, and limit queries (State or year) + massage our queries to query by agency ID  + date range the read-access will be doable (Likely won't need cstore_fdw - 14M isn't bad if the queries are simple) .

As far as generating this table, this is a mega-job. It might be worthwhile to see if we can temporarily scale up the psql instance for it.

**Comment by harrisj** [comment]
So, I would suggest we partition by state or such. Conveniently, the first 2 letters of the ORI are also usually the first two letters of the state abbr (although I'd have to look at Nebraska to see if it's the postal code or the FBI abbr).

Based on our conversation today, it seems like we could potentially merge in a "city_slug" classification or such (or such that a bunch of agencies in Chicago are tagged "chicago" and do the grouping by that. We need to figure out a good way to represent these city identifiers. Maybe we pick the ORI of a single PD within? I dunno....

**Comment by LarryBafundo** [comment]
hey so does this mean this approach will prevent us from one day adding sub offenses to the explorer?

**Comment by harrisj** [comment]
I mean, we could do suboffenses. But I think I want to see how it scales first without suboffenses and we would probably have to partition by some means first.

**Comment by harrisj** [comment]
This would probably be best handled by @cacraig to be honest

**Comment by LarryBafundo** [comment]
@cacraig okay to assign this to you?

**Comment by cacraig** [comment]
Yep! - @LarryBafundo

**Comment by cacraig** [comment]
We have generated this table in prod. We are going to verify that it's what we need to move forward on: #447     - @LarryBafundo @harrisj
