### ISSUE TITLE
Translate cryptic values in API output

### ISSUE THREAD

**Issue by catherinedevlin** [18F/crime-data-api#49]
Several fields in UCR are output as cryptically abbreviated values.  We should provide them as useful information.

Partial list of such fields:
- [ ] agency.agency_status
- [ ] agency.special_mailing_group
- [ ] state.state_fips_code
- [ ] incident.incident_status
- [ ] offense_type.hc_code
- [ ] victim.resident_status_code
- [ ] reta_month_offense_subcat.reported_status, .unfounded_status, .actual_status, etc. (0 or 3 for actual/estimated?)

**Comment by harrisj** [comment]
I think we don't need to worry about FIPS code, but some of the other statuses seem like they could use some elucidation. It seems like we have two ways of doing this:

1. Define some code lookup dicts for these values and dereference them that way
2. Add some other code tables like the ones that exist for `ref_race` etc. that we load up after we get new data from the FBI.

The second might seem more cumbersome, but I think I prefer it, since it uses the same mechanism for storage as the other tables. It does also allow us to alter FBI schema so that we can refer to these codes as foreign keys and join in on queries.

**Comment by jeremiak** [comment]
This might be in a totally different/wrong direction but I wonder if we should actually just ditch the NIBRS data model for output and craft our own incident level objects with keys we can name (and map to their relative NIBRS column) in the interest of making the output/API easier to use.

As it is right now, using the API requires a significant level of domain knowledge about what NIBRS data is and what the fields mean. In addition, that might make it easier to keep docs up to date since it will decoupled from the ingested data model.

Just an idea, interested in y'all's thoughts.

**Comment by harrisj** [comment]
It sounds like we would want to take these and move them back into the API when you are done. I understand why we started with a general query language for the backend, but it does have the risk as you point out of requiring a lot of understanding just to get started. In essence, it's like plopping people into a forest and there are no trails. Terrifying.

The Explorer will be laying down its own trails by necessity and it seems to me at least that once we have a better idea of these common interactions and their needs, we will be able to take those API tweaks and bring them back as full endpoints on the backend.

**Comment by jeremiak** [comment]
That sounds great @harrisj. I understand the value of presenting as raw of data as possible, but it also comes with the cost of adhering to a data model we didn't originate.

I think the requests that the Explorer will make are pretty basic. I listed them out in [#239](https://github.com/18F/crime-data-api/issues/239#issuecomment-270829203), but we're really only interested in filtering both summary and NIBRS data by place, time range, crime types corresponding to the Group A offenses, and flags in the data such as hate crime or human trafficking.

With those three options and endpoints for summary/trend data and NIBRS incidents, we should be able to build out the proposed Explorer views.

**Comment by harrisj** [comment]
Now that we are looking at some denormalization for NIBRS tables and also using cached JSON for representation, does this issue still apply?

**Comment by jeremiak** [comment]
I'm not sure, @harrisj. Is there an issue I can look at for the denormalization work? Sorry, I haven't seen any of that yet
