### ISSUE TITLE
How do I use the API to get information about other NIBRS offenses?

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#504]
For example, how would I make an API call to get data on the following NIBRS offenses?
* kidnapping
* bribery
* gambling

I see that there are reported offenses in the state by state NIBRS bulk download that are these offenses, but I don't see how to do it from the API documentation. I see I can use `variable` for "NIBRS summaries" endpoints but I'm not sure what that means.

**Comment by jeremiak** [comment]
It looks like I can use the `/codes` endpoint (in particular `/codes/nibrs_offense_type`) to find out the following:

Offense | Offense code
--- | ---
Kidnapping | 100
Bribery | 510
Gambling | 39D

Therefore, I can find out NIBRS related dimensions for reported kidnapping offenses with `/offenses/count/national/location_name?offense_code=100`.

How can we make these codes more apparent to the user? Are these internal identifiers that we want to expose/make part of the query interface? Do we want to promote the usage of the offense code over the offense name?

**Comment by harrisj** [comment]
So a few quick points:
1. I created the codes endpoints for us mainly as we learned about the API and it includes code tables currently that are not used in any API methods currently (for instance `nibrs_drug_type`). We might want to remove those for now.
2. We absolutely want to use codes rather than internal IDs in the API methods and should make sure to denormalize the codes into tables to make it efficient. I don't know if we are there yet.
3. I'm not sure the best way to provide the possible values to the user. Swagger does allow you to specify an `enum` argument for input parameters but this is a listing of allowed values rather than documentation of what those codes mean. We can link parameters to external documentation and I wonder if t makes sense to generate a separate Markdown file of common codes and their meaning.

**Comment by harrisj** [comment]
But to your more immediate point, the NIBRS denormalized tables like offense_counts and victim_counts only use the Offense Name and don't include the offense code currently. We should fix that. So you could pass offense_name=Kidnapping where you pass explorer_offense for now....

**Comment by harrisj** [comment]
Okay, so I did a little more digging. There are 2 ways in which lesser offenses might show up in NIBRS. In some cases, the offense will be listed as part of a `nibrs_arrestee` record, but this is really only when there is a more major offense also associated with the incident. For truly minor offenses, they only record arrests in a separate table names `nibrs_grpb_arrest` which associates with other NIBRS tables as well as a separate `nibrs_grpb_arrest_weapon` table for indicating if the arrested had 1 or more weapons (note that "Unarmed" is listed as a weapon too). This is a pretty large table of approximately **236 million rows** but we could consider segmenting it or something. Here is a query I used to create a denormalized view of the data

``` sql
select nga.grpb_arrest_id, c.ori, c.agency_name, c.state_abbr, nga.arrest_date, nga.city, nat.arrest_type_code, nat.arrest_type_name, nott.offense_category_name, nott.offense_code, nott.offense_name, nga.sex_code, na.age_code, nga.age_num, rr.race_code, rr.race_desc, ne.ethnicity_code, ne.ethnicity_name, nw.weapon_codes, nw.weapons, nga.resident_code, nga.age_range_low_num, nga.age_range_high_num 
from nibrs_grpb_arrest nga
LEFT OUTER JOIN (SELECT ngaw.grpb_arrest_id, string_agg(nwt.weapon_code::text, ', ') AS weapon_codes, string_agg(nwt.weapon_name, ', ') AS weapons FROM nibrs_grpb_arrest_weapon ngaw JOIN nibrs_weapon_type nwt ON nwt.weapon_id = ngaw.weapon_id GROUP by ngaw.grpb_arrest_id) nw ON nw.grpb_arrest_id=nga.grpb_arrest_id
JOIN nibrs_arrest_type nat ON nat.arrest_type_id = nga.arrest_type_id
JOIN nibrs_offense_type nott ON nott.offense_type_id = nga.offense_type_id
JOIN cde_agencies c ON c.agency_id = nga.agency_id
JOIN nibrs_age na ON na.age_id = nga.age_id
JOIN ref_race rr ON rr.race_id = nga.race_id
JOIN nibrs_ethnicity ne ON ne.ethnicity_id = nga.ethnicity_id
JOIN nibrs_month nm ON nm.nibrs_month_id=nga.nibrs_month_id
```

Again, we might consider slicing by year or by state or such and see how bad that is. Or we could also generate aggregate summaries from this data like we do for the regular NIBRS stuff (note that this would only be something we could mix into the offender counts, since the table doesn't really have victim information for instance)
