### ISSUE TITLE
Support ILIKE with ~ operand

### ISSUE THREAD

**Issue by cacraig** [18F/crime-data-api#67]
In addition to equality + case-insensitivity, we should allow for ILIKE operations with the ~ operand.

**Comment by cacraig** [comment]
Hey @harrisj - Wanna take a swing at this one?

**Comment by harrisj** [comment]
Sure, I can work on this. Is there a particular function in here you want me to put this functionality? Also, do we have any concerns this won't scale when we have millions of records or is that premature optimization?

**Comment by harrisj** [comment]
I think this has been done by someone. I noticed there are some ILIKE queries in there already.

In the long run though, we should consider using full text indices if we are doing text search, since that will be more performant. I don't think we have an interface for text search at the moment so I think this can be closed.
