### ISSUE TITLE
Reorder columns in the CSV to improve readability

### ISSUE THREAD

**Issue by cacraig** [18F/crime-data-api#80]
Sort output CSV columns into something reasonable. (Alphabetical, Date field first, etc.)

- [ ] Put year first on incident_counts.csv

**Comment by LarryBafundo** [comment]
have some ideas here, primarily that we should group similar elements together, such as offense code and offense description, to improve readability, especially in the expanded format. i'm not sure of the level of effort required to do this, but would require further research.

**Comment by harrisj** [comment]
In Marshmallow, we can specify that `Ordered=True` to keep columns in the same order as the DB I think. This might be enough?

**Comment by LarryBafundo** [comment]
@cacraig per our earlier conversation, here's what i was thinking for sprint 2: 

CSVs should be presented in a way that allows for the quick scanning and interpretation of their contents. Users expect to have to do some shaping of the data in their analysis, but when possible, similar data should be grouped together to promote the readability of the file. Right now the CSV presents data in no logical order, which makes it difficult to understand. 

We may consider organizing the data by segment (there are 8 NIBRS segments, see the spec. doc. for more information), where all segment data relates back to a single incident #. However, since there can be multiple victims, offenders, and arrestees per incident, each with it's own combination of circumstances, we need to differentiate between the individuals involved and the details that relate to them. 

Proposed approach: 

--Show the administrative segment first, since it's basic information about the incident and doesn't have any many to many relationships. 

--Then show the offense, victim, offender, arrestee, and property segments. 

--When there are multiple offenses, victims, offenders, and arrestees for a given incident, show segment data as numbered columns. For example, race information (an element of the victim segment) would be shown as follows, when the incident involves 3 victims: 

Victim_1_Race
Victim_2_Race
Victim_3_Race

**this will result in very wide tables, but will allow users to explore the full details of each incident.

**Comment by LarryBafundo** [comment]
<img width="669" alt="screen shot 2016-11-10 at 11 52 58 am" src="https://cloud.githubusercontent.com/assets/15899668/21402605/4d2e81e4-c787-11e6-83d1-003e589619e4.png">

**Comment by harrisj** [comment]
Following up on Ordered=True for Marshmallow, it will actually order the columns in the same way as are specified in the schema. Not sure how it works with SQLAlchemy, but I don't think those columns need to be in only one order if we want to try canonicalizing them

**Comment by LarryBafundo** [comment]
@cacraig can we close this out, at least in terms of the changes we discussed in preparation for sprint 2 testing?
