### ISSUE TITLE
expose NIBRS offense codes as endpoint

### ISSUE THREAD

**Issue by catherinedevlin** [18F/crime-data-api#86]
`/offenses/` lists summary offense taxonomy; we need to expose the NIBRS offense taxonomy, too.

**Comment by harrisj** [comment]
I suggest (and am working on) a `/codes/` endpoint that will allow users to make calls like `/codes/nibrs_activity_type` and get JSON (and potentially CSV) back. It looks like many of the code references are indeed tables in the DB (and not something I would provide as JSON), so I can just try wiring this up so I can get to know how the Marshmallow, etc flow works

**Comment by catherinedevlin** [comment]
In general, when a field has a smallish number of discrete values that a user may want to see to query for, it would be nice if they had an endpoint to see them.  That, I suppose, will correlate to tables with smallish numbers of rows that are referenced by other tables.

Running this, and eyeballing for likely candidates, I suggest...
```
SELECT schemaname,relname,n_live_tup 
  FROM pg_stat_user_tables 
  ORDER BY n_live_tup DESC
```
`nibrs_prop_desc_type`, `nibrs_offense_type`, `nibrs_location_type`, `nibrs_bias_list`, `nibrs_weapon_type`, `nibrs_relationship`, `ref_population_group`, `nibrs_suspected_drug_type`, `nibrs_circumstances`, `nibrs_criminal_act_type`, `ref_race`, `nibrs_activity_type`, `nibrs_injury`, `nibrs_prop_loss_type`, `nibrs_justifiable_force`, `nibrs_assignment_type`, `nibrs_cleared_except`, `nibrs_ethnicity`, `nibrs_using_list`

maybe also `ref_field_office`, `ref_msa`, `ref_tribe`, `ref_university`, `ref_division` - though then it gets into whether we want `ref_city` and `ref_county`, too

others should be added as we move beyond nibrs & reta into CT, HC, etc

that is a lot of tables

**Comment by harrisj** [comment]
It's a lot of tables, but I think you have already defined schema for most of them for instance so that should make it quick work. Time to make a checklist

- [ ] nibrs_prop_desc_type
- [ ] nibrs_offense_type
- [ ] nibrs_location_type
- [ ] nibrs_bias_list
- [ ] nibrs_weapon_type
- [ ] nibrs_relationship
- [ ] ref_population_group
- [ ] nibrs_suspected_drug_type
- [ ] nibrs_circumstances
- [ ] nibrs_criminal_act_type
- [ ] ref_race
- [ ] nibrs_activity_type
- [ ] nibrs_injury
- [ ] nibrs_prop_loss_type
- [ ] nibrs_justifiable_force
- [ ] nibrs_assignment_type
- [ ] nibrs_cleared_except
- [ ] nibrs_ethnicity
- [ ] nibrs_using_list
