### ISSUE TITLE
Gather data from API to support design 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#94]

**Comment by LarryBafundo** [comment]
This task is dependent on: https://github.com/18F/crime-data-api/issues/87

**Comment by jeremiak** [comment]
I've gathered data from the API now so I have a few big buckets of incidents, the largest being 54K. I'm not sure if this issue should now be closed in favor of me working with Nicole on #95.

The next steps after gathering the data are to make some very cursory plots that aren't line charts (or probably even stacked area charts) so that we can use a few different data visualization approaches in the prototype

**Comment by LarryBafundo** [comment]
@jeremiak we can close this issue.
